
PROJECT_TARGET_DIRS += .
PROJECT_SOURCEFILES += board.c

CFLAGS += -DCFG_USE_LWIP
CFLAGS += -DCS_PLATFORM=CS_P_MBED

## CPU
include ../../cpu/esp32/Makefile.inc

### RTOS 
include ../../core/sys/rtos/cmsis/freertos/Makefile.inc

