
PROJECT_TARGET_DIRS += . 
PROJECT_SOURCEFILES += board.c

# jscript uses large file
CFLAGS += -DV7_LARGE_AST

### RTOS 
include $(EMBEDX_ROOT)/core/sys/rtos/cmsis/linux/Makefile.inc

## CPU
CPU=ARM_A20
include $(EMBEDX_ROOT)/cpu/linux/Makefile.inc

